name: Code Quality

on: ['push']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check eslint
        run: |
          npm i
          npm run lint
